namespace AesEncryptionAppWinForms
{
    /// <summary>
    /// WinForms designer partial for <see cref="MainForm"/>.
    /// Declares UI components and builds the layout in <see cref="InitializeComponent"/>.
    /// </summary>
    partial class MainForm
    {
        /// <summary>
        /// Container for components that need disposing with the form.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Button that triggers file encryption workflow.
        /// </summary>
        private System.Windows.Forms.Button EncryptButton;

        /// <summary>
        /// Button that triggers file decryption workflow.
        /// </summary>
        private System.Windows.Forms.Button DecryptButton;

        /// <summary>
        /// Button to regenerate a new random Key and IV.
        /// </summary>
        private System.Windows.Forms.Button RegenerateKeyIVButton;

        /// <summary>
        /// Button to save the current Key &amp; IV into a password-protected ".key" file.
        /// </summary>
        private System.Windows.Forms.Button SaveKeyIVButton;

        /// <summary>
        /// Button to load the Key &amp; IV from a password-protected ".key" file.
        /// </summary>
        private System.Windows.Forms.Button LoadKeyIVButton;

        /// <summary>
        /// Read-only textbox used to display status, success/error messages, and output file paths.
        /// </summary>
        private System.Windows.Forms.TextBox OutputTextBox;

        /// <summary>
        /// Read-only textbox used to display the current Key and IV (Base64-encoded).
        /// </summary>
        private System.Windows.Forms.TextBox KeyIVTextBox; // New TextBox to show Key and IV

        /// <summary>
        /// Releases the unmanaged resources used by the <see cref="MainForm"/> and optionally releases the managed resources.
        /// </summary>
        /// <param name="disposing">
        /// True to dispose managed resources (components container); otherwise, false.
        /// </param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                // Dispose any components created by the designer.
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Initializes all UI components, configures their properties, and wires event handlers.
        /// This method is auto-generated by the WinForms designer.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.EncryptButton = new System.Windows.Forms.Button();
            this.DecryptButton = new System.Windows.Forms.Button();
            this.RegenerateKeyIVButton = new System.Windows.Forms.Button();
            this.SaveKeyIVButton = new System.Windows.Forms.Button();
            this.LoadKeyIVButton = new System.Windows.Forms.Button();
            this.OutputTextBox = new System.Windows.Forms.TextBox();
            this.KeyIVTextBox = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            // 
            // EncryptButton
            // 
            this.EncryptButton.Location = new System.Drawing.Point(50, 50);
            this.EncryptButton.Name = "EncryptButton";
            this.EncryptButton.Size = new System.Drawing.Size(150, 50);
            this.EncryptButton.TabIndex = 0;
            this.EncryptButton.Text = "Encrypt File";
            this.EncryptButton.UseVisualStyleBackColor = true;
            this.EncryptButton.Click += new System.EventHandler(this.EncryptButton_Click);
            // 
            // DecryptButton
            // 
            this.DecryptButton.Location = new System.Drawing.Point(250, 50);
            this.DecryptButton.Name = "DecryptButton";
            this.DecryptButton.Size = new System.Drawing.Size(150, 50);
            this.DecryptButton.TabIndex = 1;
            this.DecryptButton.Text = "Decrypt File";
            this.DecryptButton.UseVisualStyleBackColor = true;
            this.DecryptButton.Click += new System.EventHandler(this.DecryptButton_Click);
            // 
            // RegenerateKeyIVButton
            // 
            this.RegenerateKeyIVButton.Location = new System.Drawing.Point(50, 120);
            this.RegenerateKeyIVButton.Name = "RegenerateKeyIVButton";
            this.RegenerateKeyIVButton.Size = new System.Drawing.Size(350, 50);
            this.RegenerateKeyIVButton.TabIndex = 2;
            this.RegenerateKeyIVButton.Text = "Regenerate Key & IV";
            this.RegenerateKeyIVButton.UseVisualStyleBackColor = true;
            this.RegenerateKeyIVButton.Click += new System.EventHandler(this.RegenerateKeyIVButton_Click);
            // 
            // SaveKeyIVButton
            // 
            this.SaveKeyIVButton.Location = new System.Drawing.Point(50, 190);
            this.SaveKeyIVButton.Name = "SaveKeyIVButton";
            this.SaveKeyIVButton.Size = new System.Drawing.Size(150, 50);
            this.SaveKeyIVButton.TabIndex = 3;
            this.SaveKeyIVButton.Text = "Save Key & IV";
            this.SaveKeyIVButton.UseVisualStyleBackColor = true;
            this.SaveKeyIVButton.Click += new System.EventHandler(this.SaveKeyIVButton_Click);
            // 
            // LoadKeyIVButton
            // 
            this.LoadKeyIVButton.Location = new System.Drawing.Point(250, 190);
            this.LoadKeyIVButton.Name = "LoadKeyIVButton";
            this.LoadKeyIVButton.Size = new System.Drawing.Size(150, 50);
            this.LoadKeyIVButton.TabIndex = 4;
            this.LoadKeyIVButton.Text = "Load Key & IV";
            this.LoadKeyIVButton.UseVisualStyleBackColor = true;
            this.LoadKeyIVButton.Click += new System.EventHandler(this.LoadKeyIVButton_Click);
            // 
            // OutputTextBox
            // 
            this.OutputTextBox.Location = new System.Drawing.Point(50, 260);
            this.OutputTextBox.Multiline = true;
            this.OutputTextBox.Name = "OutputTextBox";
            this.OutputTextBox.ReadOnly = true;
            this.OutputTextBox.Size = new System.Drawing.Size(350, 80);
            this.OutputTextBox.TabIndex = 5;
            // 
            // KeyIVTextBox
            // 
            this.KeyIVTextBox.Location = new System.Drawing.Point(50, 360);
            this.KeyIVTextBox.Multiline = true;
            this.KeyIVTextBox.Name = "KeyIVTextBox";
            this.KeyIVTextBox.ReadOnly = true;
            this.KeyIVTextBox.Size = new System.Drawing.Size(350, 80);
            this.KeyIVTextBox.TabIndex = 6;
            // 
            // MainForm
            // 
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.ClientSize = new System.Drawing.Size(466, 480);
            this.Controls.Add(this.KeyIVTextBox);
            this.Controls.Add(this.OutputTextBox);
            this.Controls.Add(this.LoadKeyIVButton);
            this.Controls.Add(this.SaveKeyIVButton);
            this.Controls.Add(this.RegenerateKeyIVButton);
            this.Controls.Add(this.DecryptButton);
            this.Controls.Add(this.EncryptButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "MainForm";
            this.Text = "App Encryption";
            this.ResumeLayout(false);
            this.PerformLayout();

        }
    }
}
